name: CI

on:
  push:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm -w type-check

      - name: Build
        run: pnpm -w build

      - name: Tests (unit only)
        run: pnpm -w run test:ci

      - name: Lint (web)
        run: pnpm -F web lint